# Generated by Django 5.1.1 on 2024-12-12 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0003_leaveapplication_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='votes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='current_holder',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='approved_by',
            field=models.ManyToManyField(blank=True, help_text='Users who approved the leave', related_name='approved_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='current_holder',
            field=models.ManyToManyField(blank=True, related_name='holding_leaves', to=settings.AUTH_USER_MODEL),
        ),
    ]
