# Generated by Django 5.1.1 on 2024-12-12 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0005_remove_leaveapplication_votes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('nov_1', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('nov_2', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('nov_3', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('nov_4', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('percentage', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OneS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('nov_1', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('nov_2', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('nov_3', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('nov_4', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('percentage', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThreeO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('nov_1', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('nov_2', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('nov_3', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('nov_4', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('percentage', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThreeS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('nov_1', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('nov_2', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('nov_3', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('nov_4', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('percentage', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwoO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('nov_1', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('nov_2', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('nov_3', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('nov_4', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('percentage', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwoS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('nov_1', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('nov_2', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('nov_3', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('nov_4', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('percentage', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarkAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nov_1', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('nov_2', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('nov_3', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('nov_4', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Holiday', 'Holiday')], default='Holiday', max_length=10)),
                ('one_o', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_app.oneo')),
                ('one_s', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_app.ones')),
                ('three_o', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_app.threeo')),
                ('three_s', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_app.threes')),
                ('two_o', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_app.twoo')),
                ('two_s', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_app.twos')),
            ],
            options={
                'verbose_name': 'Mark Attendance',
                'verbose_name_plural': 'Mark Attendance',
            },
        ),
    ]
