# Generated by Django 5.1.1 on 2024-12-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0006_oneo_ones_threeo_threes_twoo_twos_markattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('rank', models.CharField(choices=[('cdt', 'Cadet'), ('lcpl', 'Lance Corporal'), ('cpl', 'Corporal'), ('sgt', 'Sergeant'), ('cqms', 'Company Quartermaster Sergeant'), ('csm', 'Company Sergeant Major'), ('juo', 'Junior Under Officer'), ('suo', 'Senior Under Officer'), ('ano', 'Assistant National Officer')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('aadhar_no', models.CharField(max_length=12, unique=True)),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True)),
                ('driving_license', models.CharField(blank=True, max_length=20, null=True)),
                ('register_no', models.CharField(max_length=20, unique=True)),
                ('campus', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
            ],
        ),
    ]
